package com.vitkovskaya.finalProject.service;

import com.vitkovskaya.finalProject.entity.User;
import com.vitkovskaya.finalProject.entity.UserRole;

import java.util.Map;
import java.util.Optional;

public interface UserService {

    /**
     * Search for User in database with these login and password.
     *
     * @param login    a user login
     * @param password a user password
     * @return a {@code true} if User exists, {@code false} otherwise
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    boolean findUserByLoginAndPassword(String login, String password) throws ServiceException;

    /**
     * Check if a {@code User} exists in database  with this login .
     *
     * @param login a user login
     * @return a {@code true} if User exists, {@code false} otherwise
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    boolean checkUserLogin(String login) throws ServiceException;

    /**
     * Updates a database with new password value,
     * sets this value to the current {@code User} object after the update.
     *
     * @param user        a {@code User} object to change
     * @param newPassword a new password value
     * @return {@code true} if {@code User} was updated, otherwise
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    boolean changePassword(User user, String newPassword) throws ServiceException;
    /**
     * Creates and returns (after update a database) autogenerated user id
     *
     * @param login     a login value
     * @param password  a password value
     * @param userRole  a userRole value
     * @return user id, not null
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    long registerUser(String login, String password, UserRole userRole) throws ServiceException;

    Optional<User> registerClient(Map<String, String> parameters) throws ServiceException; // FIXME: 26.02.2020

    Optional<User> registerCleaner(Map<String, String> parameters) throws ServiceException; // FIXME: 26.02.2020
    /**
     * Gets userRole id from a database using user login.
     *
     * @param login user login to find {@code User}
     * @return a founded and created int value of  userRole id
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    int getUserRoleId(String login) throws ServiceException;

    /**
     * Gets (after finding and creating) a {@code Optional<User>} object from a database using user login.
     *
     * @param login user login to find and create the {@code User} object
     * @return a founded and created {@code Optional<User>} object
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    Optional<User> findByLogin(String login) throws ServiceException;
    /**
     * Gets (after finding and creating) a {@code Optional<User>} object from a database using userId.
     *
     * @param userId a user id to find and create the {@code User} object
     * @return a founded and created {@code Optional<User>} object
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    Optional<User> findById(Long userId) throws ServiceException;

    /**
     * Updates a database with active status {@code false},
     * sets this status to the user by id.
     *
     * @param userId user id to be blocked
     * @return {@code true} if user was updated, otherwise
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    boolean blockUser(long userId) throws ServiceException;

    /**
     * Updates a database with new avatar path,
     * sets this value to the current {@code User} object after the update.
     *
     * @param userId        a id {@code User} object to change
     * @param imagePath a new avatar value
     * @return {@code true} if {@code User} was updated, otherwise
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    public boolean setUserAvatar(Long userId, String imagePath) throws ServiceException;
}
